// Generated by CoffeeScript 1.9.2
var app, express, port, router;

express = require('express');

app = new express;

port = process.env.PORT || 4000;

app.listen(port);

console.log("server running on port " + port);
